apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: gorturls.mtn.cc
spec:
  group: mtn.cc
  version: v1
  names:
    kind: GortURL
    plural: gorturls
  scope: Namespaced