/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1

import (
	"time"

	v1 "github.com/triangletodd/gort/pkg/apis/gorturl/v1"
	scheme "github.com/triangletodd/gort/pkg/client/clientset/versioned/scheme"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// GortURLsGetter has a method to return a GortURLInterface.
// A group's client should implement this interface.
type GortURLsGetter interface {
	GortURLs(namespace string) GortURLInterface
}

// GortURLInterface has methods to work with GortURL resources.
type GortURLInterface interface {
	Create(*v1.GortURL) (*v1.GortURL, error)
	Update(*v1.GortURL) (*v1.GortURL, error)
	Delete(name string, options *metav1.DeleteOptions) error
	DeleteCollection(options *metav1.DeleteOptions, listOptions metav1.ListOptions) error
	Get(name string, options metav1.GetOptions) (*v1.GortURL, error)
	List(opts metav1.ListOptions) (*v1.GortURLList, error)
	Watch(opts metav1.ListOptions) (watch.Interface, error)
	Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1.GortURL, err error)
	GortURLExpansion
}

// gortURLs implements GortURLInterface
type gortURLs struct {
	client rest.Interface
	ns     string
}

// newGortURLs returns a GortURLs
func newGortURLs(c *MtnV1Client, namespace string) *gortURLs {
	return &gortURLs{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the gortURL, and returns the corresponding gortURL object, and an error if there is any.
func (c *gortURLs) Get(name string, options metav1.GetOptions) (result *v1.GortURL, err error) {
	result = &v1.GortURL{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("gorturls").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do().
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of GortURLs that match those selectors.
func (c *gortURLs) List(opts metav1.ListOptions) (result *v1.GortURLList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1.GortURLList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("gorturls").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do().
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested gortURLs.
func (c *gortURLs) Watch(opts metav1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("gorturls").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch()
}

// Create takes the representation of a gortURL and creates it.  Returns the server's representation of the gortURL, and an error, if there is any.
func (c *gortURLs) Create(gortURL *v1.GortURL) (result *v1.GortURL, err error) {
	result = &v1.GortURL{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("gorturls").
		Body(gortURL).
		Do().
		Into(result)
	return
}

// Update takes the representation of a gortURL and updates it. Returns the server's representation of the gortURL, and an error, if there is any.
func (c *gortURLs) Update(gortURL *v1.GortURL) (result *v1.GortURL, err error) {
	result = &v1.GortURL{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("gorturls").
		Name(gortURL.Name).
		Body(gortURL).
		Do().
		Into(result)
	return
}

// Delete takes name of the gortURL and deletes it. Returns an error if one occurs.
func (c *gortURLs) Delete(name string, options *metav1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("gorturls").
		Name(name).
		Body(options).
		Do().
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *gortURLs) DeleteCollection(options *metav1.DeleteOptions, listOptions metav1.ListOptions) error {
	var timeout time.Duration
	if listOptions.TimeoutSeconds != nil {
		timeout = time.Duration(*listOptions.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Namespace(c.ns).
		Resource("gorturls").
		VersionedParams(&listOptions, scheme.ParameterCodec).
		Timeout(timeout).
		Body(options).
		Do().
		Error()
}

// Patch applies the patch and returns the patched gortURL.
func (c *gortURLs) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1.GortURL, err error) {
	result = &v1.GortURL{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("gorturls").
		SubResource(subresources...).
		Name(name).
		Body(data).
		Do().
		Into(result)
	return
}
